package ui

var messagesVI = map[string]string{
	// Docker validation
	"checking_docker":       "Đang kiểm tra Docker...",
	"docker_ok":             "Docker đã sẵn sàng",
	"docker_not_installed":  "Docker chưa được cài đặt",
	"docker_not_running":    "Docker daemon không chạy",
	"docker_not_found":      "Không tìm thấy Docker",
	"docker_daemon_stopped": "Docker không chạy",
	"docker_compose_issue":  "Vấn đề Docker Compose",
	"docker_required":       "Cần Docker để tiếp tục",

	// Docker auto-install
	"ask_install_docker":      "Tự động cài đặt Docker?",
	"ask_install_docker_desc": "Sẽ tải và cài Docker bằng script chính thức",
	"yes_install":             "Có, cài Docker",
	"no_manual":               "Không, tôi sẽ tự cài",
	"installing_docker":       "Đang cài đặt Docker...",
	"docker_installed":        "Đã cài đặt Docker thành công",
	"docker_install_failed":   "Cài đặt Docker thất bại",
	"ask_start_docker":        "Khởi động Docker daemon?",
	"starting_docker":         "Đang khởi động Docker...",
	"docker_started":          "Đã khởi động Docker daemon",
	"docker_start_failed":     "Không thể khởi động Docker",
	"docker_start_suggestion": "Khởi động Docker và chạy lại init",
	"yes":                     "Có",

	// Init flow
	"init_in_dir":          "Khởi tạo trong: %s",
	"compose_exists":       "docker-compose.yml đã tồn tại. Ghi đè?",
	"init_cancelled":       "Hủy khởi tạo",
	"loading_existing_env": "Đang tải cấu hình từ file .env hiện có",

	// Prompts
	"enable_seaweedfs": "Bật SeaweedFS file storage?",
	"seaweedfs_desc":   "SeaweedFS là hệ thống lưu trữ file phân tán",
	"enable_caddy":     "Bật Caddy web server?",
	"caddy_desc":       "Caddy là reverse proxy với tự động HTTPS",
	"enter_domain":     "Nhập domain (vd: example.com):",
	"enter_timezone":   "Nhập múi giờ (vd: Asia/Ho_Chi_Minh):",
	"yes_recommended":  "Có (khuyến nghị)",
	"no":               "Không",

	// Errors
	"error_db_password":  "Không thể tạo mật khẩu DB",
	"error_db_root_pass": "Không thể tạo mật khẩu DB root",
	"error_redis_pass":   "Không thể tạo mật khẩu Redis",
	"error_create_file":  "Lỗi khi tạo file",

	// File generation
	"generating_files": "Đang tạo các file cấu hình...",
	"files_generated":  "Các file cấu hình đã được tạo",

	// Success
	"created":       "Đã tạo: %s",
	"init_complete": "Khởi tạo hoàn tất!",

	// Next steps
	"next_steps": `
Bước tiếp theo:
  1. Kiểm tra và chỉnh sửa .env nếu cần
  2. Chạy: kk start
`,

	// Next steps for box
	"next_steps_box": `Bước tiếp theo:
  1. Kiểm tra và chỉnh sửa .env nếu cần
  2. Chạy: kk start`,

	// Language selection
	"select_language": "Chọn ngôn ngữ / Select language",
	"lang_english":    "English",
	"lang_vietnamese": "Tiếng Việt",

	// Runtime messages (start, restart, update, status)
	"stopping":                  "Đang dừng lại...",
	"preflight_checking":        "Kiểm tra trước khi chạy...",
	"preflight_failed":          "Kiểm tra thất bại. Vui lòng sửa lỗi trên",
	"preflight_checks_failed":   "Một hoặc nhiều kiểm tra thất bại",
	"starting_services":         "Khởi động services...",
	"start_failed":              "Khởi động thất bại",
	"health_checking":           "Đang kiểm tra sức khỏe dịch vụ...",
	"health_failed":             "Không thể theo dõi health",
	"some_not_ready":            "Một số dịch vụ chưa sẵn sàng. Kiểm tra: kk status",
	"start_complete":            "Khởi động hoàn tất!",
	"restarting":                "Đang khởi động lại dịch vụ...",
	"restart_failed":            "Khởi động lại thất bại",
	"restart_complete":          "Đã khởi động lại",
	"checking_updates":          "Đang kiểm tra cập nhật...",
	"pulling_images":            "Đang tải images...",
	"pull_failed":               "Không tải được images",
	"images_up_to_date":         "Tất cả images đã là phiên bản mới nhất",
	"updates_available":         "Có cập nhật:",
	"confirm_restart":           "Khởi động lại services với images mới?",
	"update_cancelled":          "Hủy cập nhật. Images đã được tải, chạy 'kk restart' để áp dụng",
	"confirm_update_recreate":   "Tạo lại containers với images mới?",
	"update_recreate_cancelled": "Hủy cập nhật. Images đã được tải, containers chưa được tạo lại",
	"recreating":                "Đang khởi động lại với images mới...",
	"recreate_failed":           "Recreate thất bại",
	"update_complete":           "Cập nhật hoàn tất!",
	"no_services":               "Không có dịch vụ nào đang chạy",
	"run_start":                 "Chạy: kk start",
	"no_services_defined":       "Không có dịch vụ nào được định nghĩa trong docker-compose.yml",
	"run_init":                  "Chạy: kk init",
	"all_stopped":               "Tất cả dịch vụ đã dừng",
	"status_summary_stopped":    "%d dịch vụ đã dừng\nĐể khởi động KKEngine, chạy: kk start",
	"all_running":               "Tất cả %d dịch vụ đang chạy",
	"some_running":              "%d/%d dịch vụ đang chạy",
	"get_status_failed":         "Không lấy được trạng thái",
	"start_summary_success":     "Tất cả %d dịch vụ đã khởi động thành công",
	"start_summary_partial":     "%d/%d dịch vụ đã khởi động\nKiểm tra logs: docker compose logs",
	"restart_summary_success":   "Tất cả %d dịch vụ đã khởi động lại thành công",
	"restart_summary_partial":   "%d/%d dịch vụ đã khởi động lại\nKiểm tra logs: docker compose logs",
	"update_summary_success":    "Tất cả %d dịch vụ đã cập nhật thành công",
	"update_summary_partial":    "%d/%d dịch vụ đã cập nhật\nKiểm tra logs: docker compose logs",

	// Table columns
	"service_status": "Trạng thái dịch vụ",
	"access_info":    "Thông tin truy cập",
	"col_service":    "Dịch vụ",
	"col_status":     "Trạng thái",
	"col_health":     "Sức khỏe",
	"col_ports":      "Cổng",
	"col_url":        "URL",
	"col_setting":    "Cài đặt",
	"col_value":      "Giá trị",

	// Access URLs
	"main_url":       "URL chính",
	"manager_system": "Quản lý",

	// Init summary
	"config_summary":   "Tóm tắt cấu hình",
	"created_files":    "Các file đã tạo",
	"enabled":          "Bật",
	"disabled":         "Tắt",
	"domain":           "Tên miền",
	"install_location": "Vị trí cài đặt",
	"data_directories": "Thư mục dữ liệu",

	// Status display
	"status_running":  "Đang chạy",
	"status_stopped":  "Đã dừng",
	"status_starting": "Đang khởi động",
	"summary":         "Tóm tắt",

	// Init wizard steps
	"step_license":      "Xác thực License",
	"step_docker_check": "Kiểm tra Docker",
	"step_language":     "Chọn ngôn ngữ",
	"step_options":      "Tùy chọn cấu hình",
	"step_domain":       "Cấu hình domain",
	"step_credentials":  "Cấu hình môi trường",
	"step_generate":     "Tạo file",
	"step_complete":     "Hoàn tất",

	// License verification
	"enter_license":             "Nhập license key của bạn",
	"license_required":          "License key là bắt buộc",
	"license_invalid_format":    "Định dạng license không hợp lệ. Mong đợi: LICENSE-XXXXXXXXXXXXXXXX",
	"validating_license":        "Đang xác thực license...",
	"license_validated":         "Xác thực license thành công",
	"license_validation_failed": "Xác thực license thất bại",
	"license_check_key":         "Vui lòng kiểm tra license key và thử lại",

	// Credentials / Environment Configuration
	"ask_use_random":      "Sử dụng mật khẩu tự động tạo?",
	"ask_use_random_desc": "Các mật khẩu ngẫu nhiên an toàn đã được tạo sẵn",
	"no_edit":             "Không, để tôi chỉnh sửa",
	"group_system":        "Cấu hình hệ thống",
	"group_db_secrets":    "Mật khẩu Database",
	"group_s3_secrets":    "Mật khẩu S3 Storage",
	"error_jwt_secret":    "Không thể tạo JWT secret",
	"error_s3_access_key": "Không thể tạo S3 access key",
	"error_s3_secret_key": "Không thể tạo S3 secret key",

	// Force mode messages
	"docker_not_installed_force_init":      "Docker chưa cài đặt (force mode - tiếp tục)",
	"docker_daemon_not_running_force_init": "Docker daemon không chạy (force mode - tiếp tục)",
	"docker_compose_issue_force_init":      "Phát hiện vấn đề Docker Compose (force mode - tiếp tục)",
	"compose_exists_force_init":            "docker-compose.yml đã tồn tại, ghi đè trong force mode",

	// Validation
	"error_invalid_domain": "Định dạng domain không hợp lệ (dùng example.com hoặc localhost)",

	// Preflight
	"check":  "Kiểm tra",
	"result": "Kết quả",

	// Start/Restart/Update steps
	"step_preflight":      "Kiểm tra trước",
	"step_start_services": "Khởi động dịch vụ",
	"step_health_check":   "Kiểm tra sức khỏe",
	"step_status":         "Trạng thái",
	"step_pull_images":    "Tải images",
	"step_recreate":       "Tạo lại containers",

	// Stop command
	"step_stop_services": "Dừng dịch vụ",
	"stopping_services":  "Đang dừng dịch vụ...",
	"stop_failed":        "Dừng thất bại",
	"stop_complete":      "Tất cả dịch vụ đã dừng",
	"stop_desc":          "Dừng tất cả dịch vụ",

	// Remove command
	"step_remove_services": "Xóa dịch vụ",
	"removing_services":    "Đang xóa containers và networks...",
	"remove_failed":        "Xóa thất bại",
	"remove_complete":      "Đã xóa tất cả containers và networks",
	"removed_containers":   "Đã xóa containers và networks",
	"removed_with_volumes": "Đã xóa containers, networks và volumes",
	"remove_desc":          "Xóa tất cả containers",

	// Container conflict errors
	"container_conflict_suggestion": "Containers từ project khác đang sử dụng cùng tên. Hãy xóa chúng trước",

	// Command banners
	"status_desc":  "Trạng thái dịch vụ",
	"init_desc":    "Khởi tạo Docker Stack",
	"start_desc":   "Khởi động tất cả dịch vụ",
	"restart_desc": "Khởi động lại tất cả dịch vụ",
	"update_desc":  "Cập nhật & Khởi tạo lại",

	// Error box
	"to_fix":   "Để khắc phục",
	"then_run": "Sau đó chạy",

	// Table columns (new)
	"col_image":   "Image",
	"col_current": "Hiện tại",
	"col_new":     "Mới",
	"col_file":    "Tệp",

	// Progress
	"starting":         "đang khởi động...",
	"ready":            "sẵn sàng",
	"unhealthy":        "không khỏe mạnh",
	"services_started": "Đã khởi động dịch vụ",

	// Selfupdate
	"step_check_update":     "Kiểm tra cập nhật",
	"step_install_update":   "Cài đặt cập nhật",
	"checking_cli_update":   "Đang kiểm tra cập nhật...",
	"check_update_failed":   "Không thể kiểm tra cập nhật",
	"current_version":       "Phiên bản hiện tại",
	"latest_version":        "Phiên bản mới nhất",
	"cli_up_to_date":        "kk CLI đã là phiên bản mới nhất",
	"update_available":      "Có phiên bản mới!",
	"to_update_run":         "Để cập nhật, chạy",
	"confirm_cli_update":    "Cập nhật lên phiên bản mới nhất?",
	"selfupdate_cancelled":  "Đã hủy cập nhật",
	"downloading_update":    "Đang tải và cài đặt...",
	"update_install_failed": "Không thể cài đặt cập nhật",
	"selfupdate_complete":   "Cập nhật thành công!",
	"selfupdate_desc":       "Cập nhật kk CLI",

	// Project configuration
	"project_not_configured": "Chưa cấu hình Project",
	"run_init_to_configure":  "Chạy 'kk init' trong thư mục project của bạn",
	"config_load_failed":     "Không thể tải cấu hình",
	"config_title":           "Cấu hình:",
	"config_language":        "Ngôn ngữ",
	"config_project_dir":     "Thư mục Project",
	"config_file_path":       "File cấu hình",
	"config_not_set":         "(chưa thiết lập)",

	// n8n Management
	"n8n_install_desc":           "Thiết lập n8n Workflow Automation",
	"n8n_check_existing":         "Kiểm tra cài đặt hiện có",
	"n8n_already_installed":      "n8n đã được cài đặt",
	"n8n_overwrite_prompt":       "n8n đã cài đặt. Ghi đè cấu hình?",
	"n8n_overwrite_desc":         "Dữ liệu hiện có (workflows, credentials) sẽ được giữ lại",
	"n8n_domain_config":          "Cấu hình Domain",
	"n8n_enter_domain":           "Nhập domain cho n8n",
	"n8n_domain_desc":            "vd: n8n.example.com hoặc localhost cho truy cập local",
	"n8n_generate_credentials":   "Tạo Credentials",
	"n8n_connect_kkengine":       "Kết nối với mạng kkengine?",
	"n8n_connect_kkengine_desc":  "Cho phép n8n truy cập trực tiếp các dịch vụ kkengine",
	"n8n_encryption_key_warning": "Quan trọng: Lưu Encryption Key",
	"n8n_encryption_key_desc":    "Key này dùng để mã hóa credentials trong n8n.\nNếu bạn mất key này, bạn không thể khôi phục dữ liệu đã mã hóa.\nHãy lưu lại một cách an toàn!",
	"n8n_encryption_key_confirm": "Tôi đã lưu encryption key",
	"n8n_credentials_desc":       "Credentials ngẫu nhiên an toàn đã được tạo",
	"n8n_db_password":            "Mật khẩu Database",
	"n8n_encryption_key":         "Encryption Key (QUAN TRỌNG: không được mất!)",
	"n8n_generate_files":         "Tạo Cấu hình",
	"n8n_generating":             "Đang tạo cấu hình n8n...",
	"n8n_generate_failed":        "Không thể tạo cấu hình",
	"n8n_files_generated":        "Đã tạo các file cấu hình",
	"n8n_install_summary":        "Tóm tắt Cài đặt",
	"n8n_ready_to_start":         "Sẵn sàng Khởi động",
	"n8n_start_now":              "Khởi động n8n ngay?",
	"n8n_install_complete":       "Cài đặt n8n hoàn tất!",
	"n8n_run_start":              "Chạy 'kk n8n start' khi sẵn sàng",
	"n8n_not_installed":          "n8n chưa được cài đặt. Chạy 'kk n8n install' trước.",
	"n8n_starting":               "Đang khởi động n8n...",
	"n8n_started":                "n8n đang chạy",
	"n8n_stopping":               "Đang dừng n8n...",
	"n8n_stopped":                "n8n đã dừng",

	// Unified error suggestions
	"err_fix_issues":                    "Sửa các lỗi trên và thử lại",
	"err_check_docker_logs":             "Kiểm tra Docker logs để biết chi tiết",
	"err_check_docker_pull":             "Kiểm tra kết quả docker pull và khả năng truy cập image",
	"err_check_internet":                "Kiểm tra kết nối internet hoặc thử lại sau",
	"err_invalid_init_input":            "Dữ liệu init không hợp lệ",
	"err_invalid_init_input_suggestion": "Dùng đúng một nguồn license và cung cấp --domain, --language hợp lệ.",
	"err_compose_file_missing":          "Đảm bảo docker-compose.yml tồn tại",
	"err_check_docker_running":          "Kiểm tra Docker có đang chạy không",
	"err_docker_permission":             "Thêm user vào nhóm docker",
	"err_docker_permission_command":     "sudo usermod -aG docker $USER && newgrp docker",
	"err_cancelled":                     "Đã hủy",
	"err_unknown":                       "Lỗi: %v",
	"err_install_n8n_first":             "Cài n8n trước",
	"err_nothing_to_remove":             "Không có gì để xóa",
	"err_title_n8n_not_installed":       "n8n chưa cài đặt",
	"err_title_port_in_use":             "Cổng 5678 đang được dùng",
	"err_port_in_use_msg":               "Cổng 5678 đang được dùng bởi %s (PID %d)",
	"err_port_in_use_suggestion":        "Dừng dịch vụ đang dùng cổng 5678 hoặc đổi cổng n8n",
	"err_title_n8n_start_failed":        "Không thể khởi động n8n",
	"err_title_docker_required":         "Cần Docker",
	"err_install_docker_first":          "Cài Docker trước",
	"err_check_services_running":        "Kiểm tra dịch vụ có đang chạy không",
	"err_pull_internet":                 "Kiểm tra kết nối internet hoặc trạng thái Docker Hub",
	"err_update_prepare_suggestion":     "Đảm bảo docker-compose.yml tồn tại và Docker có thể inspect images",
	"err_update_permissions":            "Thử chạy với sudo hoặc kiểm tra quyền",
	"warn_skipping_license":             "Bỏ qua xác thực license (chế độ test)",
	"warn_cannot_load_config":           "Không thể tải cấu hình",

	// Health and preflight display
	"health_healthy":                   "khỏe mạnh",
	"health_unhealthy":                 "không khỏe",
	"health_starting":                  "đang khởi động",
	"preflight_pass":                   "Đạt",
	"preflight_result_failed":          "Thất bại",
	"preflight_check_docker_installed": "Docker cài đặt",
	"preflight_check_docker_daemon":    "Docker daemon",
	"preflight_check_ports":            "Cổng mạng",
	"preflight_check_env":              "File .env",
	"preflight_check_compose":          "docker-compose.yml",
	"preflight_check_caddyfile":        "Caddyfile",
	"preflight_check_disk":             "Dung lượng disk",
	"preflight_fix_install_docker":     "Cài Docker",
	"preflight_fix_start_docker":       "Khởi động Docker daemon",
	"preflight_fix_stop_conflicting":   "Dừng dịch vụ xung đột hoặc đổi cổng",
	"preflight_fix_create_env":         "Tạo file .env",
	"preflight_fix_create_compose":     "Tạo hoặc sửa docker-compose.yml",
	"preflight_fix_create_caddyfile":   "Tạo hoặc sửa Caddyfile",
	"preflight_disk_warning":           "Chỉ còn %.1fGB, khuyến nghị >= %dGB",
	"preflight_table_render_failed":    "Không thể hiển thị bảng preflight: %v",

	// Validator warnings
	"warn_env_permissions":               "Cảnh báo: quyền .env quá mở (%o)",
	"warn_env_permissions_fix":           "Thiết lập quyền: chmod 600 .env (chỉ owner đọc/ghi)",
	"warn_weak_password":                 "Cảnh báo: mật khẩu yếu cho: %s (nên >= 16 ký tự)",
	"warn_env_world_readable":            "Cảnh báo: .env có thể bị người khác đọc.",
	"warn_env_world_readable_fix":        "Chạy: chmod 600 %s",
	"warn_disk_low":                      "Cảnh báo: disk thấp (%.1fGB). Khuyến nghị ít nhất %dGB.",
	"warn_compose_version_read":          "Cảnh báo: không đọc được phiên bản Docker Compose (%s)",
	"warn_docker_permissions_fix_failed": "Cảnh báo: không sửa được quyền Docker: %v",
	"warn_docker_group_add_failed":       "Cảnh báo: không thêm user vào nhóm docker: %v",

	// Runtime display
	"cmd_start_title":                             "kk start",
	"cmd_status_title":                            "kk status",
	"cmd_update_title":                            "kk update",
	"cmd_restart_title":                           "kk restart",
	"unhealthy_services_hint":                     "%d dịch vụ không khỏe: %s",
	"unhealthy_services_logs":                     "Xem logs: docker compose logs %s",
	"health_failed_detail":                        "%s: %v",
	"n8n_access_url":                              "Truy cập n8n tại: %s",
	"n8n_running_at":                              "n8n đang chạy tại: %s",
	"n8n_run_status_hint":                         "Chạy 'kk n8n status' để xem chi tiết",
	"n8n_run_install_hint":                        "Chạy 'kk n8n install' để thiết lập n8n.",
	"n8n_update_success":                          "Cập nhật n8n thành công!",
	"n8n_data_preserved":                          "Dữ liệu được giữ tại %s",
	"n8n_remove_volume_warning":                   "CẢNH BÁO: Thao tác này sẽ xóa toàn bộ dữ liệu n8n!",
	"n8n_remove_volume_warning_desc":              "Workflows, credentials và database sẽ mất vĩnh viễn.",
	"docker_compose_logs_command":                 "docker compose logs",
	"docker_start_command":                        "sudo systemctl start docker",
	"docker_install_suggestion":                   "Cài Docker tại: https://docs.docker.com/get-docker/",
	"docker_install_failed_suggestion":            "Cài Docker thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_curl_missing":             "Cần curl để cài Docker",
	"docker_install_err_curl_missing_suggestion":  "Cài curl rồi thử lại, hoặc cài Docker thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_sudo_missing":             "Cần sudo để cài Docker",
	"docker_install_err_sudo_missing_suggestion":  "Chạy với quyền root hoặc cài Docker thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_sudo_password":            "Cần mật khẩu sudo để cài Docker",
	"docker_install_err_sudo_password_suggestion": "Nhập mật khẩu sudo khi được hỏi. Nếu không thấy prompt, chạy sudo -v trước hoặc cài thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_network":                  "Không thể tải script cài Docker",
	"docker_install_err_network_suggestion":       "Kiểm tra mạng tới get.docker.com hoặc cài thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_timeout":                  "Cài Docker quá thời gian chờ",
	"docker_install_err_timeout_suggestion":       "Thử lại với timeout dài hơn (KK_DOCKER_INSTALL_TIMEOUT=10m) hoặc cài thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_pkg_lock":                 "Package manager đang bị khóa",
	"docker_install_err_pkg_lock_suggestion":      "Đợi package manager xong rồi thử lại hoặc cài thủ công: https://docs.docker.com/get-docker/",
	"docker_install_err_generic":                  "Cài Docker thất bại",
	"docker_install_err_generic_suggestion":       "Cài thủ công: https://docs.docker.com/get-docker/",
	"docker_daemon_wait_timeout":                  "Docker daemon chưa sẵn sàng sau khi khởi động",
	"docker_daemon_wait_timeout_suggestion":       "Thử: sudo systemctl start docker && docker info",
	"docker_permission_not_effective":             "Đã thêm user vào nhóm docker nhưng quyền chưa có hiệu lực",
	"docker_permission_not_effective_suggestion":  "Chạy: newgrp docker hoặc đăng nhập lại, rồi thử lại",
	"err_docker_manual_install_suggestion":        "Cài Docker tại https://docs.docker.com/get-docker/ hoặc chạy lại với --force để bỏ qua preflight.",
	"err_docker_compose_update_suggestion":        "Cập nhật Docker lên bản mới nhất hoặc chạy lại với --force để bỏ qua preflight.",
	"docker_check_network_command":                "curl -I https://get.docker.com",
	"docker_sudo_password_hint":                   "Bạn có thể được yêu cầu nhập mật khẩu sudo bên dưới.",

	// Validator UserError keys
	"docker_permission_denied":            "Không có quyền truy cập Docker",
	"docker_permission_denied_suggestion": "Thêm user vào nhóm docker hoặc dùng sudo",
	"compose_not_found":                   "Không tìm thấy Docker Compose",
	"compose_not_found_suggestion":        "Cài Docker Compose v2",
	"compose_version_old":                 "Docker Compose quá cũ (%s), cần >= v2.0",
	"compose_version_old_suggestion":      "Cập nhật Docker Compose: https://docs.docker.com/compose/install/",
	"env_stat_error":                      "Không đọc được thông tin file .env",
	"env_stat_error_suggestion":           "Kiểm tra quyền truy cập file",
	"env_parse_error":                     "Không phân tích được file .env",
	"env_parse_error_suggestion":          "Kiểm tra cú pháp file .env",
	"env_missing_suggestion":              "Chạy: kk init",
	"env_missing_vars_suggestion":         "Thêm vào .env: %s",
	"compose_read_error":                  "Không đọc được docker-compose.yml",
	"compose_read_error_suggestion":       "Kiểm tra quyền file",
	"compose_no_services":                 "Không có dịch vụ trong docker-compose.yml",
	"compose_no_services_suggestion":      "Chạy: kk init",
	"caddy_read_error":                    "Không đọc được Caddyfile",
	"caddy_read_error_suggestion":         "Kiểm tra quyền file",
	"caddy_empty":                         "Caddyfile trống",
	"caddy_empty_suggestion":              "Chạy: kk init",
	"port_conflict":                       "Phát hiện xung đột cổng",
	"port_conflict_suggestion":            "Xem chi tiết bên dưới",
	"compose_syntax_error_suggestion":     "Kiểm tra YAML: indentation, colons, quotes",
	"compose_missing":                     "Không tìm thấy file docker-compose.yml",
}
