package ui

var messagesEN = map[string]string{
	// Docker validation
	"checking_docker":                 "Checking Docker...",
	"docker_ok":                       "Docker is ready",
	"docker_not_installed":            "Docker is not installed",
	"docker_not_running":              "Docker daemon is not running",
	"docker_not_found":                "Docker Not Found",
	"docker_daemon_stopped":           "Docker Not Running",
	"docker_permission_pending_title": "Docker Group Membership Pending",
	"docker_compose_issue":            "Docker Compose Issue",
	"docker_required":                 "Docker is required to continue",

	// Docker auto-install
	"ask_install_docker":              "Install Docker automatically?",
	"ask_install_docker_desc":         "Downloads and installs Docker from get.docker.com (may take a few minutes)",
	"yes_install":                     "Yes, install Docker",
	"no_manual":                       "No, I'll install manually",
	"installing_docker":               "Installing Docker...",
	"docker_install_in_progress_note": "Using the official install script from get.docker.com. This may take a few minutes.",
	"docker_installed":                "Docker installed successfully",
	"docker_installed_daemon_running": "Docker is installed and the daemon is running",
	"docker_group_activate_note":      "Your user was added to the docker group. Run newgrp docker in this shell, then run kk init again.",
	"docker_install_failed":           "Docker installation failed",
	"ask_start_docker":                "Start Docker daemon?",
	"starting_docker":                 "Starting Docker daemon...",
	"docker_started":                  "Docker daemon started",
	"docker_start_failed":             "Failed to start Docker",
	"docker_start_suggestion":         "Start Docker and run init again",
	"yes":                             "Yes",

	// Init flow
	"init_in_dir":          "Initializing in: %s",
	"compose_exists":       "docker-compose.yml already exists. Overwrite?",
	"init_cancelled":       "Initialization cancelled",
	"loading_existing_env": "Loading configuration from existing .env file",

	// Prompts
	"enable_seaweedfs": "Enable SeaweedFS file storage?",
	"seaweedfs_desc":   "SeaweedFS is a distributed file storage system",
	"enable_caddy":     "Enable Caddy web server?",
	"caddy_desc":       "Caddy is a reverse proxy with automatic HTTPS",
	"enter_domain":     "Enter domain (e.g. example.com):",
	"enter_timezone":   "Enter timezone (e.g. Asia/Ho_Chi_Minh):",
	"yes_recommended":  "Yes (recommended)",
	"no":               "No",

	// Errors
	"error_db_password":  "Failed to generate DB password",
	"error_db_root_pass": "Failed to generate DB root password",
	"error_redis_pass":   "Failed to generate Redis password",
	"error_create_file":  "Failed to create file",

	// File generation
	"generating_files": "Generating configuration files...",
	"files_generated":  "Configuration files generated",

	// Success
	"created":       "Created: %s",
	"init_complete": "Initialization complete!",

	// Next steps
	"next_steps": `
Next steps:
  1. Review and edit .env if needed
  2. Run: kk start
`,

	// Next steps for box
	"next_steps_box": `Next steps:
  1. Review and edit .env if needed
  2. Run: kk start`,

	// Language selection
	"select_language": "Select language / Chọn ngôn ngữ",
	"lang_english":    "English",
	"lang_vietnamese": "Tiếng Việt",

	// Runtime messages
	"stopping":                  "Stopping...",
	"preflight_checking":        "Running preflight checks...",
	"preflight_failed":          "Preflight checks failed. Please fix the errors above",
	"preflight_checks_failed":   "One or more preflight checks failed",
	"starting_services":         "Starting services...",
	"start_failed":              "Start failed",
	"health_checking":           "Checking service health...",
	"health_failed":             "Cannot monitor health",
	"some_not_ready":            "Some services not ready. Check: kk status",
	"start_complete":            "Start complete!",
	"restarting":                "Restarting services...",
	"restart_failed":            "Restart failed",
	"restart_complete":          "Restart complete",
	"checking_updates":          "Checking for updates...",
	"pulling_images":            "Pulling images...",
	"pull_failed":               "Failed to pull images",
	"images_up_to_date":         "All images are up to date",
	"updates_available":         "Updates available:",
	"confirm_restart":           "Restart services with new images?",
	"update_cancelled":          "Update cancelled. Images downloaded, run 'kk restart' to apply",
	"confirm_update_recreate":   "Recreate containers with new images?",
	"update_recreate_cancelled": "Update cancelled. Images downloaded, containers were not recreated",
	"recreating":                "Recreating with new images...",
	"recreate_failed":           "Recreate failed",
	"update_complete":           "Update complete!",
	"no_services":               "No services running",
	"run_start":                 "Run: kk start",
	"no_services_defined":       "No services defined in docker-compose.yml",
	"run_init":                  "Run: kk init",
	"all_stopped":               "All services stopped",
	"status_summary_stopped":    "%d services stopped\nTo start KKEngine, run: kk start",
	"all_running":               "All %d services running",
	"some_running":              "%d/%d services running",
	"get_status_failed":         "Failed to get status",
	"start_summary_success":     "All %d services started successfully",
	"start_summary_partial":     "%d/%d services started\nCheck logs: docker compose logs",
	"restart_summary_success":   "All %d services restarted successfully",
	"restart_summary_partial":   "%d/%d services restarted\nCheck logs: docker compose logs",
	"update_summary_success":    "All %d services updated successfully",
	"update_summary_partial":    "%d/%d services updated\nCheck logs: docker compose logs",

	// Table columns
	"service_status": "Service Status",
	"access_info":    "Access Information",
	"col_service":    "Service",
	"col_status":     "Status",
	"col_health":     "Health",
	"col_ports":      "Ports",
	"col_url":        "URL",
	"col_setting":    "Setting",
	"col_value":      "Value",

	// Access URLs
	"main_url":       "Main URL",
	"manager_system": "Manager",

	// Init summary
	"config_summary":   "Configuration Summary",
	"created_files":    "Created Files",
	"enabled":          "Enabled",
	"disabled":         "Disabled",
	"domain":           "Domain",
	"install_location": "Installation Location",
	"data_directories": "Data Directories",

	// Status display
	"status_running":  "Running",
	"status_stopped":  "Stopped",
	"status_starting": "Starting",
	"summary":         "Summary",

	// Init wizard steps
	"step_license":      "License Verification",
	"step_docker_check": "Docker Check",
	"step_language":     "Language Selection",
	"step_options":      "Configuration Options",
	"step_domain":       "Domain Configuration",
	"step_credentials":  "Environment Configuration",
	"step_generate":     "Generate Files",
	"step_complete":     "Complete",

	// License verification
	"enter_license":             "Enter your license key",
	"license_required":          "License key is required",
	"license_invalid_format":    "Invalid license format. Expected: LICENSE-XXXXXXXXXXXXXXXX",
	"validating_license":        "Validating license...",
	"license_validated":         "License validated successfully",
	"license_validation_failed": "License validation failed",
	"license_check_key":         "Please check your license key and try again",

	// Credentials / Environment Configuration
	"ask_use_random":      "Use auto-generated secrets?",
	"ask_use_random_desc": "Secure random secrets have been generated for all fields",
	"no_edit":             "No, let me edit",
	"group_system":        "System Configuration",
	"group_db_secrets":    "Database Secrets",
	"group_s3_secrets":    "S3 Storage Secrets",
	"error_jwt_secret":    "Failed to generate JWT secret",
	"error_s3_access_key": "Failed to generate S3 access key",
	"error_s3_secret_key": "Failed to generate S3 secret key",

	// Force mode messages
	"docker_not_installed_force_init":      "Docker not installed (force mode - continuing)",
	"docker_daemon_not_running_force_init": "Docker daemon not running (force mode - continuing)",
	"docker_compose_issue_force_init":      "Docker Compose issue detected (force mode - continuing)",
	"compose_exists_force_init":            "docker-compose.yml exists, overwriting in force mode",

	// Validation
	"error_invalid_domain": "Invalid domain format (use example.com or localhost)",

	// Preflight
	"check":  "Check",
	"result": "Result",

	// Start/Restart/Update steps
	"step_preflight":      "Preflight Checks",
	"step_start_services": "Start Services",
	"step_health_check":   "Health Check",
	"step_status":         "Status",
	"step_pull_images":    "Pull Images",
	"step_recreate":       "Recreate Containers",

	// Stop command
	"step_stop_services": "Stop Services",
	"stopping_services":  "Stopping services...",
	"stop_failed":        "Stop failed",
	"stop_complete":      "All services stopped",
	"stop_desc":          "Stop All Services",

	// Remove command
	"step_remove_services": "Remove Services",
	"removing_services":    "Removing containers and networks...",
	"remove_failed":        "Remove failed",
	"remove_complete":      "All containers and networks removed",
	"removed_containers":   "Containers and networks removed",
	"removed_with_volumes": "Containers, networks, and volumes removed",
	"remove_desc":          "Remove All Containers",

	// Container conflict errors
	"container_conflict_suggestion": "Containers from another project are using the same names. Remove them first",

	// Command banners
	"status_desc":  "Service Status",
	"init_desc":    "Docker Stack Initialization",
	"start_desc":   "Start All Services",
	"restart_desc": "Restart All Services",
	"update_desc":  "Pull & Recreate",

	// Error box
	"to_fix":   "To fix",
	"then_run": "Then run",

	// Table columns (new)
	"col_image":   "Image",
	"col_current": "Current",
	"col_new":     "New",
	"col_file":    "File",

	// Progress
	"starting":         "starting...",
	"ready":            "ready",
	"unhealthy":        "unhealthy",
	"services_started": "Services started",

	// Selfupdate
	"step_check_update":     "Check for Updates",
	"step_install_update":   "Install Update",
	"checking_cli_update":   "Checking for updates...",
	"check_update_failed":   "Failed to check for updates",
	"current_version":       "Current version",
	"latest_version":        "Latest version",
	"cli_up_to_date":        "kk CLI is already up to date",
	"update_available":      "A new version is available!",
	"to_update_run":         "To update, run",
	"confirm_cli_update":    "Update to the latest version?",
	"selfupdate_cancelled":  "Update cancelled",
	"downloading_update":    "Downloading and installing...",
	"update_install_failed": "Failed to install update",
	"selfupdate_complete":   "Successfully updated!",
	"selfupdate_desc":       "Update kk CLI",

	// Project configuration
	"project_not_configured": "Project Not Configured",
	"run_init_to_configure":  "Run 'kk init' in your project folder",
	"config_load_failed":     "Failed to load configuration",
	"config_title":           "Configuration:",
	"config_language":        "Language",
	"config_project_dir":     "Project Dir",
	"config_file_path":       "Config File",
	"config_not_set":         "(not set)",

	// n8n Management
	"n8n_install_desc":           "n8n Workflow Automation Setup",
	"n8n_check_existing":         "Check Existing Installation",
	"n8n_already_installed":      "n8n is already installed",
	"n8n_overwrite_prompt":       "n8n already installed. Overwrite configuration?",
	"n8n_overwrite_desc":         "Existing data (workflows, credentials) will be preserved",
	"n8n_domain_config":          "Domain Configuration",
	"n8n_enter_domain":           "Enter n8n domain",
	"n8n_domain_desc":            "e.g., n8n.example.com or localhost for local access",
	"n8n_generate_credentials":   "Generate Credentials",
	"n8n_connect_kkengine":       "Connect to kkengine network?",
	"n8n_connect_kkengine_desc":  "Allows n8n to access kkengine services directly",
	"n8n_encryption_key_warning": "Important: Save Your Encryption Key",
	"n8n_encryption_key_desc":    "This key is used to encrypt your credentials in n8n.\nIf you lose this key, you cannot recover encrypted data.\nSave it securely!",
	"n8n_encryption_key_confirm": "I have saved the encryption key",
	"n8n_credentials_desc":       "Secure random credentials have been generated",
	"n8n_db_password":            "Database Password",
	"n8n_encryption_key":         "Encryption Key (IMPORTANT: never lose this!)",
	"n8n_generate_files":         "Generate Configuration",
	"n8n_generating":             "Generating n8n configuration...",
	"n8n_generate_failed":        "Failed to generate configuration",
	"n8n_files_generated":        "Configuration files generated",
	"n8n_install_summary":        "Installation Summary",
	"n8n_ready_to_start":         "Ready to Start",
	"n8n_start_now":              "Start n8n now?",
	"n8n_install_complete":       "n8n installation complete!",
	"n8n_run_start":              "Run 'kk n8n start' when ready",
	"n8n_not_installed":          "n8n is not installed. Run 'kk n8n install' first.",
	"n8n_starting":               "Starting n8n services...",
	"n8n_started":                "n8n is running",
	"n8n_stopping":               "Stopping n8n services...",
	"n8n_stopped":                "n8n stopped",

	// Unified error suggestions
	"err_fix_issues":                    "Fix the issues above and try again",
	"err_check_docker_logs":             "Check Docker logs for details",
	"err_check_docker_pull":             "Check Docker pull output and image availability",
	"err_check_internet":                "Check internet connection or try again later",
	"err_invalid_init_input":            "Invalid init input",
	"err_invalid_init_input_suggestion": "Use exactly one license source and provide valid --domain and --language flags.",
	"err_compose_file_missing":          "Make sure docker-compose.yml exists",
	"err_check_docker_running":          "Check if Docker is running",
	"err_docker_permission":             "Add user to docker group",
	"err_docker_permission_command":     "sudo usermod -aG docker $USER && newgrp docker",
	"err_cancelled":                     "Cancelled",
	"err_unknown":                       "Error: %v",
	"err_install_n8n_first":             "Install n8n first",
	"err_nothing_to_remove":             "Nothing to remove",
	"err_title_n8n_not_installed":       "n8n Not Installed",
	"err_title_port_in_use":             "Port 5678 In Use",
	"err_port_in_use_msg":               "Port 5678 is being used by %s (PID %d)",
	"err_port_in_use_suggestion":        "Stop the service using port 5678 or change n8n port",
	"err_title_n8n_start_failed":        "Failed to start n8n",
	"err_title_docker_required":         "Docker Required",
	"err_install_docker_first":          "Install Docker first",
	"err_check_services_running":        "Check if services are running",
	"err_pull_internet":                 "Check internet connection or Docker Hub status",
	"err_update_prepare_suggestion":     "Make sure docker-compose.yml exists and Docker can inspect images",
	"err_update_permissions":            "Try running with sudo or check permissions",
	"warn_skipping_license":             "Skipping license validation (test mode)",
	"warn_cannot_load_config":           "Cannot load config",

	// Health and preflight display
	"health_healthy":                   "healthy",
	"health_unhealthy":                 "unhealthy",
	"health_starting":                  "starting",
	"preflight_pass":                   "Pass",
	"preflight_result_failed":          "Failed",
	"preflight_check_docker_installed": "Docker installed",
	"preflight_check_docker_daemon":    "Docker daemon",
	"preflight_check_ports":            "Network ports",
	"preflight_check_env":              ".env file",
	"preflight_check_compose":          "docker-compose.yml",
	"preflight_check_caddyfile":        "Caddyfile",
	"preflight_check_disk":             "Disk space",
	"preflight_fix_install_docker":     "Install Docker",
	"preflight_fix_start_docker":       "Start Docker daemon",
	"preflight_fix_stop_conflicting":   "Stop conflicting services or change ports",
	"preflight_fix_create_env":         "Create .env file",
	"preflight_fix_create_compose":     "Create or fix docker-compose.yml",
	"preflight_fix_create_caddyfile":   "Create or fix Caddyfile",
	"preflight_disk_warning":           "Only %.1fGB free, recommend >= %dGB",
	"preflight_table_render_failed":    "Failed to render preflight table: %v",

	// Validator warnings
	"warn_env_permissions":               "Warning: .env permissions too open (%o)",
	"warn_env_permissions_fix":           "Set permissions: chmod 600 .env (owner read/write only)",
	"warn_weak_password":                 "Warning: weak password for: %s (should be >= 16 characters)",
	"warn_env_world_readable":            "Warning: .env may be readable by others.",
	"warn_env_world_readable_fix":        "Run: chmod 600 %s",
	"warn_disk_low":                      "Warning: low disk space (%.1fGB). Recommend at least %dGB.",
	"warn_compose_version_read":          "Warning: cannot read Docker Compose version (%s)",
	"warn_docker_permissions_fix_failed": "Could not fix Docker permissions: %v",
	"warn_docker_group_add_failed":       "Could not add user to the docker group: %v",

	// Runtime display
	"cmd_start_title":                             "kk start",
	"cmd_status_title":                            "kk status",
	"cmd_update_title":                            "kk update",
	"cmd_restart_title":                           "kk restart",
	"unhealthy_services_hint":                     "%d service(s) unhealthy: %s",
	"unhealthy_services_logs":                     "View logs: docker compose logs %s",
	"health_failed_detail":                        "%s: %v",
	"n8n_access_url":                              "Access n8n at: %s",
	"n8n_running_at":                              "n8n is running at: %s",
	"n8n_run_status_hint":                         "Run 'kk n8n status' for details",
	"n8n_run_install_hint":                        "Run 'kk n8n install' to set up n8n.",
	"n8n_update_success":                          "n8n updated successfully!",
	"n8n_data_preserved":                          "Data preserved in %s",
	"n8n_remove_volume_warning":                   "WARNING: This will delete all n8n data!",
	"n8n_remove_volume_warning_desc":              "Workflows, credentials, and database will be permanently lost.",
	"docker_compose_logs_command":                 "docker compose logs",
	"docker_start_command":                        "sudo systemctl start docker",
	"docker_install_suggestion":                   "Install Docker at: https://docs.docker.com/get-docker/",
	"docker_install_failed_suggestion":            "Install Docker manually: https://docs.docker.com/get-docker/",
	"docker_install_err_curl_missing":             "curl is required to install Docker",
	"docker_install_err_curl_missing_suggestion":  "Install curl and retry, or install Docker manually: https://docs.docker.com/get-docker/",
	"docker_install_err_sudo_missing":             "sudo is required to install Docker",
	"docker_install_err_sudo_missing_suggestion":  "Run as root or install Docker manually: https://docs.docker.com/get-docker/",
	"docker_install_err_sudo_password":            "sudo password is required to install Docker",
	"docker_install_err_sudo_password_suggestion": "Enter your sudo password when prompted. If the prompt does not appear, run sudo -v first or install Docker manually: https://docs.docker.com/get-docker/",
	"docker_install_err_network":                  "Cannot download the Docker install script",
	"docker_install_err_network_suggestion":       "Check network access to get.docker.com or install manually: https://docs.docker.com/get-docker/",
	"docker_install_err_timeout":                  "Docker installation timed out",
	"docker_install_err_timeout_suggestion":       "Retry with a longer timeout (KK_DOCKER_INSTALL_TIMEOUT=10m) or install manually: https://docs.docker.com/get-docker/",
	"docker_install_err_pkg_lock":                 "Package manager is locked",
	"docker_install_err_pkg_lock_suggestion":      "Wait for the package manager to finish, then retry or install manually: https://docs.docker.com/get-docker/",
	"docker_install_err_generic":                  "Docker installation failed",
	"docker_install_err_generic_suggestion":       "Install manually: https://docs.docker.com/get-docker/",
	"docker_daemon_wait_timeout":                  "Docker daemon is not ready after startup",
	"docker_daemon_wait_timeout_suggestion":       "Try: sudo systemctl start docker && docker info",
	"docker_permission_not_effective":             "Docker is running, but your user cannot access it in this shell yet",
	"docker_permission_not_effective_suggestion":  "Run newgrp docker in this shell, or log in again, then run kk init",
	"err_docker_manual_install_suggestion":        "Install Docker from https://docs.docker.com/get-docker/ or rerun with --force to bypass preflight checks.",
	"err_docker_compose_update_suggestion":        "Update Docker to the latest version or rerun with --force to bypass preflight checks.",
	"docker_check_network_command":                "curl -I https://get.docker.com",
	"docker_sudo_password_hint":                   "Enter your sudo password when prompted (usually once).",
	"docker_permission_denied":                    "Docker permission denied",
	"docker_permission_denied_suggestion":         "Add user to docker group or use sudo",
	"compose_not_found":                           "Docker Compose not found",
	"compose_not_found_suggestion":                "Install Docker Compose v2",
	"compose_version_old":                         "Docker Compose version too old (%s), requires >= v2.0",
	"compose_version_old_suggestion":              "Update Docker Compose: https://docs.docker.com/compose/install/",
	"env_stat_error":                              "Cannot read .env file info",
	"env_stat_error_suggestion":                   "Check file access permissions",
	"env_parse_error":                             "Cannot parse .env file",
	"env_parse_error_suggestion":                  "Check .env file syntax",
	"env_missing_suggestion":                      "Run: kk init",
	"env_missing_vars_suggestion":                 "Add to .env: %s",
	"compose_read_error":                          "Cannot read docker-compose.yml",
	"compose_read_error_suggestion":               "Check file permissions",
	"compose_no_services":                         "No services defined in docker-compose.yml",
	"compose_no_services_suggestion":              "Run: kk init",
	"caddy_read_error":                            "Cannot read Caddyfile",
	"caddy_read_error_suggestion":                 "Check file permissions",
	"caddy_empty":                                 "Caddyfile is empty",
	"caddy_empty_suggestion":                      "Run: kk init",
	"port_conflict":                               "Port conflict detected",
	"port_conflict_suggestion":                    "See details below",
	"compose_syntax_error_suggestion":             "Check YAML: indentation, colons, quotes",
	"compose_missing":                             "docker-compose.yml file not found",
}
